### ISSUE TITLE
Inspector hides equipment color index

### ISSUE THREAD

**Issue by FortunesTeam** [risk-of-thunder/RoR2EditorKit#12]
![image](https://github.com/user-attachments/assets/fef96414-82d3-491b-a1a4-6c4ab8742975)
![image](https://github.com/user-attachments/assets/65722c21-ce4f-4f28-ae9a-be0d33944f11)

**Comment by Nebby1999** [comment]
Technically resolved as theres no longer an EquipmentDef inspector, lol
