### ISSUE TITLE
Yaml shaders fix is missing

### ISSUE THREAD

**Issue by KingEnderBrine** [risk-of-thunder/RoR2EditorKit#8]
https://github.com/risk-of-thunder/RoR2EditorKit/blob/9357f701244d285d976da58955232dbce669ea73/CHANGELOG.md?plain=1#L11

But it's nowhere to be found

**Comment by Nebby1999** [comment]
i actuallly have no idea where i left it, i'm going to release a new version alongside a fix for Hitbox gizmos where it doesnt draw the rotation

**Comment by Nebby1999** [comment]
Fixed in release 4.0.2
